#!/bin/sh
set -o errexit -o nounset -o pipefail

exec > /var/log/late-commands-stdout
exec 2> /var/log/late-commands-stderr

/simple-kvm-preseed-lib/iptables-ssh-only
/simple-kvm-preseed-lib/serial-console-only
/simple-kvm-preseed-lib/unattended-upgrades
/examples/root-authorized-keys
/simple-kvm-preseed-lib/exim4
