#!/bin/sh
set -o errexit -o nounset -o pipefail

chown -R root:root for-target-etc
chmod -R 644 for-target-etc
cp /for-target-etc/ntp.conf /target/etc/ntp.conf
cp -R /for-target-etc/iptables /target/etc/iptables

mkdir /target/root/.ssh
chmod 700 /target/root/.ssh
cp /authorized_keys /target/root/.ssh/authorized_keys
chmod 600 /target/root/.ssh/authorized_keys

chroot /target /bin/systemctl disable getty@tty1.service console-setup.service
