#!/bin/sh
set -o errexit -o nounset

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

mkfs.ext4 -F /dev/vda
mkdir /target
mount -t ext4 /dev/vda /target
mkdir /target/etc

cat > /target/etc/fstab <<EOF
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/vda        /               ext4    errors=remount-ro,relatime,discard      0       1
proc            /proc           proc    defaults        0       0
sysfs           /sys            sysfs   defaults        0       0
tmpfs           /dev/shm        tmpfs   defaults        0       0
devpts          /dev/pts        devpts  defaults        0       0
EOF
