#!/bin/sh
set -o errexit -o nounset
set -x

. /preseed-settings

chmod 700 .ssh
chmod 600 .ssh/authorized_keys

ip link set eth0 up
ip addr add $IP4/24 broadcast $IP4_BCAST dev eth0
ip route add default via $IP4_GATEWAY

ip addr add $IP6 dev eth0
ip route add $IP6_GATEWAY dev eth0
ip route add default via $IP6_GATEWAY

cat > /etc/resolv.conf <<EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
EOF
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname

cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address $IP4
    netmask $IP4_NETMASK
    network $IP4_NETWORK
    broadcast $IP4_BCAST
    gateway $IP4_GATEWAY

iface eth0 inet6 static
    address $IP6
    netmask 128
    post-up /sbin/ip -family inet6 route add $IP6_GATEWAY dev eth0
    post-up /sbin/ip -family inet6 route add default via $IP6_GATEWAY
    pre-down /sbin/ip -family inet6 route del default via $IP6_GATEWAY
    pre-down /sbin/ip -family inet6 route del $IP6_GATEWAY dev eth0
EOF

rm bin/ethdetect bin/netcfg
touch bin/ethdetect bin/netcfg
chmod +x bin/ethdetect bin/netcfg
