#!/bin/sh
set -o errexit -o nounset -o pipefail

chown -R root:root for-target-etc
chmod -R 644 for-target-etc
cp /for-target-etc/ntp.conf /target/etc/ntp.conf
cp -R /for-target-etc/iptables /target/etc/iptables

mkdir /target/root/.ssh
chmod 700 /target/root/.ssh
cp /.ssh/authorized_keys /target/root/.ssh/
chmod 600 /target/root/.ssh/authorized_keys

in-target git clone https://github.com/danielrichman/simple-kvm /usr/local/lib/simple-kvm
cp /target/usr/local/lib/simple-kvm/example-config.json /target/etc/guests.json
cp /target/usr/local/lib/simple-kvm/sysctl.conf         /target/etc/sysctl.conf
ln -s /usr/local/lib/simple-kvm/guest-manager /target/usr/local/bin
ln -s /usr/local/lib/simple-kvm/random-mac    /target/usr/local/bin

# TODO exim
