#!/bin/sh
set -o errexit -o nounset -o pipefail

exec > /var/log/late-commands-stdout
exec 2> /var/log/late-commands-stderr

chown -R root:root /for-target-etc
chmod -R 644 /for-target-etc
cp /for-target-etc/ntp.conf /target/etc/ntp.conf
cp /for-target-etc/apt.conf.d/20auto-upgrades /for-target-etc/apt.conf.d/50unattended-upgrades /target/etc/apt/apt.conf.d
mkdir -p /target/etc/iptables
cp /for-target-etc/iptables/rules.v4 /for-target-etc/iptables/rules.v6 /target/etc/iptables

mkdir /target/root/.ssh
chmod 700 /target/root/.ssh
cp /.ssh/authorized_keys /target/root/.ssh/
chmod 600 /target/root/.ssh/authorized_keys

mkdir /target/usr/local/lib/simple-kvm
# It will be root:staff g+s by default
chown root:root /target/usr/local/lib/simple-kvm
chmod 755 /target/usr/local/lib/simple-kvm

in-target git clone https://github.com/danielrichman/simple-kvm /usr/local/lib/simple-kvm
cp /target/usr/local/lib/simple-kvm/example-config.json /target/etc/guests.json
cp /target/usr/local/lib/simple-kvm/sysctl.conf         /target/etc/sysctl.conf
ln -s /usr/local/lib/simple-kvm/guest-manager /target/usr/local/bin
ln -s /usr/local/lib/simple-kvm/random-mac    /target/usr/local/bin

# TODO exim, raid monitoring
