#!/bin/sh
set -o errexit -o nounset

. /usr/share/debconf/confmodule

# At the time of writing, busybox-ash has a bug where errexit is not 
# correctly propagated through subshells :-(. This function propagates
# the failure.
exit_if_subshell_returned_nonzero () { 
    RET=$?; [ $RET -eq 0 ] || exit $RET
}

log() {
    logger -t run-ansible "$@"
}

echo "log ansible-at-exit done" > /ansible-infra/at-exit
trap 'log ansible-at-exit; . /ansible-infra/at-exit' EXIT

for bindmount in ansible-playbooks ansible-infra; do
    log "bind-mounting ${bindmount}"
    mkdir -p /target/${bindmount}
    sed -i "1irmdir /target/${bindmount}" /ansible-infra/at-exit
    mount -o bind /${bindmount} /target/${bindmount}
    sed -i "1iumount /target/${bindmount}" /ansible-infra/at-exit
done

# The installer doesn't appear to set this up? Python multiprocessing needs it.
log "mounting /dev/shm"
if [ ! -d /dev/shm ]; then
    mkdir /dev/shm
    mount -t tmpfs tmpfs /dev/shm
fi

log "installing ansible"

db_progress INFO run-ansible/progress/installing-ansible
# It looks like ansible depends on python3-distutils, but the package doesn't
# know that, so we have to explicitly install it here.
in-target \
  debconf-apt-progress --from 100 --to 150 --logstderr -- \
  apt install ansible python3-distutils --no-install-recommends --yes

db_progress STOP

if grep ^HOST4= /preseed-settings 2> /dev/null; then
    ( . /preseed-settings
      mkdir -p /target/etc/ansible/facts.d
      ( echo "[networking]"
        echo "host4=${HOST4}" ) > /target/etc/ansible/facts.d/simple_kvm.fact )
fi

echo "$(hostname) ansible_connection=local ansible_python_interpreter=/usr/bin/python3" \
  > /target/etc/ansible/hosts

log "running playbook"

( export ANSIBLE_LOCAL_TMP=/ansible-infra/tmp
  export ANSIBLE_LOG_PATH=/ansible-infra/ansible.log
  export ANSIBLE_CALLBACK_PLUGINS=/ansible-infra/callback-plugins
  in-target \
      ansible-playbook /ansible-playbooks/main.yml \
            --extra-vars '{"debian_installer": true}' \
    || ( log "ansible failed"
         db_input critical run-ansible/progress/running-ansible-failed || true
         db_go || true
         exit 10 ) )
exit_if_subshell_returned_nonzero

log "done running playbook"
