#!/bin/sh
set -o errexit -o nounset -o pipefail

in-target apt-get install -f exim4-daemon-light
rm -f /target/etc/exim4/exim4.conf.template
rm -f /target/etc/exim4/passwd.client
rm -rf /target/etc/exim4/conf.d

cp /preseed-lib/exim4.conf /target/tmp/exim4.conf
in-target install -o root -g root -m 644  /tmp/exim4.conf /etc/exim4/exim4.conf

. /preseed-settings
cat > /target/etc/exim4/hostnames.conf <<EOF
HOSTNAME=$HOSTNAME
FQDN=$FQDN
EOF

in-target openssl genrsa -out /etc/exim4/dkim.key 2048
in-target chown root:Debian-exim /etc/exim4/dkim.key
chmod 640 /target/etc/exim4/dkim.key
in-target openssl rsa \
    -in /etc/exim4/dkim.key \
    -out /etc/exim4/dkim.public.key \
    -pubout -outform PEM
