#!/bin/sh

# Intended for use in late-commands, applies an iptables config to the target.

set -o errexit -o nounset

mkdir -m 755 -p /target/etc/iptables

cat > /target/tmp/rules.v4 <<EOF
*filter

`cat /preseed-lib/iptables-rules.v4-common`

-A INPUT -j REJECT

COMMIT
EOF

in-target install -o root -g root -m 644 /tmp/rules.v4 /etc/iptables/rules.v4

cat > /target/tmp/rules.v6 <<EOF
*filter

`cat /preseed-lib/iptables-rules.v6-common`

-A INPUT -j REJECT

COMMIT
EOF

in-target install -o root -g root -m 644 /tmp/rules.v6 /etc/iptables/rules.v6
