#!/bin/sh
set -o errexit -o nounset

# When the VM has no console, these items slow down the boot a lot as it waits
# for them to timeout (or something?)
chroot /target /bin/systemctl disable getty@tty1.service console-setup.service
