#!/bin/sh
set -o errexit -o nounset

. /usr/share/debconf/confmodule

if [ -z ${EARLY_COMMANDS+x} ]; then
    # I don't understand why this happens.
    logger -t manual-partitioning "refusing to run during early-commands"
    exit 1;
fi

logger -t manual-partitioning "disabling partman"
rm /var/lib/dpkg/info/partman-base.postinst
touch /var/lib/dpkg/info/partman-base.postinst
chmod +x /var/lib/dpkg/info/partman-base.postinst

logger -t manual-partitioning "running /manual-partition"
exec /manual-partition
