#!/bin/sh
set -o errexit -o nounset

. /usr/share/debconf/confmodule

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

logger -t manual-partitioning "disabling partman"
rm /var/lib/dpkg/info/partman-base.postinst
touch /var/lib/dpkg/info/partman-base.postinst
chmod +x /var/lib/dpkg/info/partman-base.postinst

logger -t manual-partitioning "running /manual-partition"
exec /manual-partition
