#!/bin/sh

# Intended for use in late-commands. Configures the debian-installer
# to use kexec to start the system, rather than rebooting. Particularly
# useful since it allows you to reboot without installing a bootloader.

set -o errexit -o nounset

in-target apt install --yes --no-install-recommends kexec-tools
in-target kexec -l /vmlinuz --initrd=/initrd.img \
     --append="console=ttyS0,115200n8 net.ifnames=0 root=/dev/vda"

# We used to use `anna-install kexec-tools-udeb` and `kexec -e` below, however
# the udeb is borked: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1138292
# Fortunately we have gcc in /target :vomit:

cat > /target/tmp/kexec-e.c <<EOF
#include <unistd.h>
#include <sys/reboot.h>
#include <linux/reboot.h>

int main(int argc, char **argv) {
    sync();
    reboot(LINUX_REBOOT_CMD_KEXEC);
    return 1;
}
EOF

in-target gcc -o /tmp/kexec-e /tmp/kexec-e.c
cp /target/tmp/kexec-e /lib/debian-installer/exit
