#!/bin/sh

# Intended to be used in early-commands. Brings up the networking, and writes 
# /etc/network/interfaces, which will later be copied by d-i into the guest.

set -o errexit -o nounset
set -x

. /preseed-settings
echo "static-guest-networking: IP4=$IP4, IP6=$IP6, HOST4=$HOST4, HOSTNAME=$HOSTNAME"

ip link set eth0 up
ip addr add $IP4/32 dev eth0
ip route add $HOST4 dev eth0
ip route add default via $HOST4

ip addr add $IP6/128 dev eth0
ip route add fe80::1 dev eth0
ip route add default via fe80::1 dev eth0

cat > /etc/resolv.conf <<EOF
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
EOF
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname

# in debian 9 we needed "sleep 10" before adding the v6 default route because
# we had to wait for DAD. in debian 10 ifupdown does that for you
cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address $IP4
    netmask 255.255.255.255
    post-up /sbin/ip route add $HOST4 dev eth0
    post-up /sbin/ip route add default via $HOST4 src $IP4

iface eth0 inet6 static
    address $IP6
    netmask 128
    post-up /sbin/ip -family inet6 route add default via fe80::1 dev eth0 src $IP6

source-directory /etc/network/interfaces.d
EOF

rm bin/ethdetect bin/netcfg
touch bin/ethdetect bin/netcfg
chmod +x bin/ethdetect bin/netcfg
