#!/bin/sh
set -o errexit -o nounset -o pipefail

exec > /var/log/late-commands2-stdout
exec 2> /var/log/late-commands2-stderr

chown -R root:root /preseed-files2
chmod -R 644 /preseed-files2

mkdir -p /target/etc/iptables
cp /preseed-files2/iptables/rules.v4 /preseed-files2/iptables/rules.v6 /target/etc/iptables

mkdir /target/root/.ssh
chmod 700 /target/root/.ssh
cp /preseed-files2/authorized_keys /target/root/.ssh/authorized_keys
chmod 600 /target/root/.ssh/authorized_keys

if [ -f /late-commands3 ]; then /late-commands3; fi
